from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER SEQUENCE student_id_seq RENAME TO student_id_old_seq')
    op.execute('CREATE SEQUENCE student_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1')
    op.execute('ALTER TABLE student ALTER COLUMN id SET DEFAULT nextval(\'student_id_seq\')')
    op.alter_column('student', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.execute('DROP SEQUENCE student_id_old_seq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER SEQUENCE student_id_seq RENAME TO student_id_new_seq')
    op.execute('CREATE SEQUENCE student_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1')
    op.execute('ALTER TABLE student ALTER COLUMN id SET DEFAULT nextval(\'student_id_seq\')')
    op.alter_column('student', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.execute('DROP SEQUENCE student_id_new_seq')
    # ### end Alembic commands ###
